apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: dev-db
  name: dev-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dev-db
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/crud-rest-line-bot-app-network: "true"
        io.kompose.service: dev-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: nest
            - name: POSTGRES_PASSWORD
              value: "123"
            - name: POSTGRES_USER
              value: postgres
          image: postgres:13
          name: postgres
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
      restartPolicy: Always
